fullnameOverride: mysql

image:
  repository: registry.hub.docker.com/library
  # name: arm64v8/mysql
  name: mysql
  # tag: 5.7.32
  tag: 8.0.29-oracle
  pullPolicy: IfNotPresent
  # args:
  #   - "--ignore-db-dir=lost+found"

platform: linux/arm64/v8
restart: always

ports:
  - containerPort: 3306

service:
  ports:
    - port: 3306
